spring:
  application:
    name: prueba-tecnica-luis

  datasource:
    url: 'jdbc:h2:mem:inditex'
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    properties:
      hibernate:
        show_sql: false
        format_sql: false
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      mode: always


server:
  port: 8080
  error:
    include-message: always
lombok:
  addLombokGeneratedAnnotation: true

app:
  version: @project.version@

logging:
  level:
    root: INFO
